default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: postgres
  password: '123456789'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: todolist_development
test:
  <<: *default
  database: todolist_test
production:
  <<: *default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: todolist_production
  username: postgres
  password: '123456789'
  pool: 20